# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: destro.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://destro.me" # the base hostname & protocol for your site

gravatar: b0fdc38f853e5fc1809a209f6caaf0f9
email:
web: http://www.bbqcode.it
google_plus: 106300469229847540771
linkedin: fdestro
#twitter:
github: dexpota

t:
  en:
    back: "Back"
    toc: "Table of contents"
    language: "language"
    license: "License"
    not_available: "not available in"
    making:
      tools: "Tools"
      materials: "Materials"
      gallery: "Gallery"
    footer:
      built_with: "Built with Jekyll, theme based on <a href='https://github.com/nrandecker/particle'>particle</a> by <a href='https://nrandecker.github.io'>Nathan Randecker</a>"
    homepage:
      username: "Destro Fabrizio"
      user_title: "Software engineer"
      about_me: "About me"
      projects: "Projects"
      expertise: "Expertise"
      user_description: "Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS."
      languages: "Languages"
      software: "Software"
      hardware: "Hardware"
  it:
    back: "Indietro"
    toc: "Indice"
    language: "lingua"
    license: "Licenza"
    not_available: "non disponibile in"
    about_me: "Su di me"
    projects: "Progetti"
    user_title: "Software engineer"
    making:
      tools: "Strumentazioni"
      materials: "Materiali"
      gallery: "Galleria"
    footer:
      built_with: "Costruito con Jekyll, tema basato su <a href='https://github.com/nrandecker/particle'>particle</a> di <a href='https://nrandecker.github.io'>Nathan Randecker</a>"
    homepage:
      username: "Destro Fabrizio"
      user_title: "Software engineer"
      about_me: "Su di me"
      projects: "Progetti"
      expertise: "Competenze"
      user_description: "Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS."
      languages: "Linguaggi"
      software: "Software"
      hardware: "Hardware"

collections:
  projects:
    output: true
    permalink: /:collection/:path/


compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]

# User settings
username: Destro Fabrizio
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Build settings
markdown: kramdown
theme: minima
